-- dbt model patch: fix_paysim_raw_transactions_amount_type.sql
-- Auto-generated by AI Data Reliability Agent
-- Add this to your dbt project's models/ directory

{{ config(
    materialized='view',
    description='Fixes schema drift on amount column - casts back to DOUBLE PRECISION'
) }}

SELECT
    step,
    type,
    CAST(amount AS DOUBLE PRECISION) AS amount,  -- FIX: Cast back to numeric
    nameOrig,
    oldbalanceOrg,
    newbalanceOrig,
    nameDest,
    oldbalanceDest,
    newbalanceDest,
    isFraud,
    isFlaggedFraud,
    -- Recompute derived features with correct types
    CAST(amount AS DOUBLE PRECISION) / NULLIF(oldbalanceOrg, 0) AS amount_ratio,
    oldbalanceOrg - newbalanceOrig AS balance_change_orig,
    newbalanceDest - oldbalanceDest AS balance_change_dest,
    CASE WHEN CAST(amount AS DOUBLE PRECISION) > 200000 THEN 1 ELSE 0 END AS is_large_transaction
FROM {{ source('paysim', 'paysim_raw_transactions') }}
